name: Deployment Checks

on:
  push:
    branches:
      - main
  deployment:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0'

      - name: Install dependencies
        run: |
          make create-environment
          make requirements

      - name: Run All Checks
        run: |
          make dev-setup
          make run-checks
