name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

  build-and-test-extract:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies extract
        run: |
          make create-environment
          make requirements-extract
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-extract

  build-and-test-transform:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies transform
        run: |
          make create-environment
          make requirements-transform
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-transform

  build-and-test-load:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies load
        run: |
          make create-environment
          make requirements-load
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-load

  deploy-docker-transform:
    needs: build-and-test-transform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: build image
        run: |
          make build
          make tag
          make ecr-login
          make push
          make deploy      


  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    needs: [build-and-test-extract,deploy-docker-transform]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve