name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

  build-and-test-extract:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies extract
        run: |
          make create-environment
          make requirements-extract
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-extract

  build-and-test-transform:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies transform
        run: |
          make create-environment
          make requirements-transform
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-transform

  build-and-test-load:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies load
        run: |
          make create-environment
          make requirements-load
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-load
  
  deploy-ecr:
    name: deploy-ecr
    runs-on: ubuntu-latest
    needs: [build-and-test-extract, build-and-test-transform] #, build-and-test-load ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform/terraform_ecr
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform/terraform_ecr
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform/terraform_ecr
        run: terraform apply -auto-approve

      

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: deploy-ecr
    steps:
      - name: Check that the image builds
        uses: actions/checkout@v4
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build transform image
        run: |
          make build-transform
      - name: Tag transform image
        run: |
          make tage-transform
      - name: Push docker image to ecr
        run: |
          make push transform 
   
      

  # deploy-docker-transform:
  #   needs: [setup-docker,build-and-test-transform]
  #   runs-on: ubuntu-latest
  #   env:
  #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  #     REGION: ${{ secrets.AWS_REGION }}
  #     PROFILE: default
  #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
  #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     aws-region: ${{ secrets.AWS_REGION }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with: 
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}
  #     - name: build image
  #       run: |
  #         make push
  #         make deploy      


  
  deploy-terraform:
    name: deploy-terraform
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform/terraform_ecr
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform/terraform_ecr
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform/terraform_ecr
        run: terraform apply -auto-approve        
  