name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0'

  install-dependencies:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make create-environment
          make requirements

  run-tests:
    needs: install-dependencies  # Ensures dependencies are installed before running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Development Checks
        run: |
          make dev-setup
          make run-checks
