name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

  build-and-test-extract:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies extract
        run: |
          make create-environment
          make requirements-extract
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-extract

  build-and-test-transform:
    needs: setup-python  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies transform
        run: |
          make create-environment
          make requirements-transform
          make dev-setup

      - name: Run Development Checks
        run: |
          make run-checks-transform

  # build-and-test-transform:
  #   needs: setup-python  
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Install dependencies transform
  #       run: |
  #         make create-environment
  #         make requirements-transform
  #         make dev-setup

  #     - name: Run Development Checks
  #       run: |
  #         make run-checks-transform

